# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

digitize <- function(x, bins, min = 0L, max = 256L) {
    .Call(`_fastGLCM_digitize`, x, bins, min, max)
}

deg2rad <- function(x) {
    .Call(`_fastGLCM_deg2rad`, x)
}

fast_glcm <- function(img, vmin = 0L, vmax = 255L, levels = 8L, kernel_size = 5L, distance = 1.0, angle = 0.0, threads = 1L) {
    .Call(`_fastGLCM_fast_glcm`, img, vmin, vmax, levels, kernel_size, distance, angle, threads)
}

method_exists <- function(methods, this_method) {
    .Call(`_fastGLCM_method_exists`, methods, this_method)
}

fast_GLCM <- function(img, methods, levels = 8L, kernel_size = 5L, distance = 1.0, angle = 0.0, threads = 1L, dir_save = NULL) {
    .Call(`_fastGLCM_fast_GLCM`, img, methods, levels, kernel_size, distance, angle, threads, dir_save)
}

