
#...............................................
# Update the python directory code once per week
#...............................................

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches: master

name: update code of python directory

jobs:
  blogdown:
    name: update-python-code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: remove and clone the python-glcm repository
        working-directory: ${{ github.workspace }}
        run: |
          rm -r inst/GLCM_Python_Code
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git clone https://github.com/tzm030329/GLCM.git inst/GLCM_Python_Code
          git add --all
          git diff-index --quiet HEAD || git commit -am "update the 'GLCM_Python_Code' directory"
          git push
